import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/libs/Providers/Providers";
import NextUINavbar from "@/components/sheard/Navbar/Navbar";
import Footer from "@/components/sheard/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Growth guard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NextUINavbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
